<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/TerrainBuilder.App/TerrainBuilder.App.csproj" />
    <ProjectReference Include="../../src/TerrainBuilder.Infrastructure/TerrainBuilder.Infrastructure.csproj" />
  </ItemGroup>
</Project>
